version: "3"
services:
  mysql:
    container_name: mydb
    image: javatest3mysql
    hostname: root
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    expose:
    - "3306"

    


